### ISSUE TITLE
项目安装后报SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.

### ISSUE THREAD

**Issue by fozero** [jiangqqlmj/GaGaMall#17]
项目安装后报SyntaxError:Strict mode does not allow function declaration in a lexically nested statement.

**Comment by TomCruiseYang** [comment]
我也遇到了,求教...

**Comment by andyliuzs** [comment]
这个问题有解答吗?

**Comment by FH910619** [comment]
这个有人知道怎么解决吗？我也遇到这个问题了

**Comment by FH910619** [comment]
后来我找到原因了，这个是由于react-native的版本过低导致的，升级react native就可以了
在package.json中，改成  
"react": "^16.0.0-alpha.12",
 "react-native": "^0.46.0",
然后npm install重新构建就好了
