### ISSUE TITLE
Cannot evaluate module react-native-vector-icons : Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by lpslpsl** [jiangqqlmj/GaGaMall#2]
按照你的步骤从git clone 下来、。然后npm install之后运行出现Cannot evaluate module react-native-vector-icons : Configuration with name 'default' not found.。初次接触RN，不太明白

**Comment by jiangqqlmj** [comment]
解决方案:
android/settings.gradle文件下面删除如下代码:
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

然后android/app/build.gradle删除如下代码:
compile project(':react-native-vector-icons')

或者你重新clone一份代码吧，我刚刚重新上传的。

**Comment by lpslpsl** [comment]
好的好的。谢谢
